#!/usr/bin/env python

import sys
from xdiagnose.x_pkg_names import debpkg_to_fdopkg

if len(sys.argv) < 2:
    print "Usage: %prog <package-name>"
    sys.exit(1)

print debpkg_to_fdopkg(sys.argv[1])
