#!/usr/bin/env python

import sys
from xdiagnose.x_pkg_names import fdopkg_to_debpkg

if len(sys.argv) < 2:
    print "Usage: %prog <package-name>"
    sys.exit(1)

print fdopkg_to_debpkg(sys.argv[1])
