#!/bin/bash

# Must run as root, from inside the dir with all the .dsc files.
# Results assumed to go to /var/cache/pbuilder/result/

# Include the bash library functions
. $(dirname $0)/xorg-pkg-tools.lib

usage() {
    write_msg "Usage: $0"
    exit 1
}

# TODO:  Should this work on a per-package basis?
for file in *.dsc ; do
    pball $file > ${file%.dsc}.log 2>&1

    # TODO:  Parse output from pball to get info about debs

    # TODO:  Copy deb(s) to destination place and rename

    # TODO:  Link to the package json file?
    # Generate new JSON file for the deb
    echo > ${file%.dsc}.json <<EOF
{
    "debs":         "",
    "dbg-debs":     "",
    "distro":       "${distro}"
}
EOF
done
