#!/bin/bash

# Include the bash library functions
. $(dirname $0)/xorg-pkg-tools.lib

usage() {
    write_msg "Usage: $0 <pkg-conf-file>"
    exit 1
}

PKG_CONF=$1
[ ! -e "${PKG_CONF}" ] && usage
. ${PKG_CONF}

[ -d ${GIT_DIR} ] || die "Error:  Missing directory ${GIT_DIR}"
cd ${GIT_DIR}

msg "git-commit-log -c $TAG_PATTERN > ../${PKG_CONF%.config}.commits"
git-commit-log -cr ${TAG_PATTERN} > ../${PKG_CONF%.config}.commits
