#!/bin/bash

# Include the bash library functions
. $(dirname $0)/xorg-pkg-tools.lib

PKG=$1

if [ -z $PKG ] ; then
   echo "Usage:  $0 <package-name>"
   exit 1
fi

if [ -d "hist-snap" ] ; then
   cd hist-snap
fi

if [ ! -e "${PKG}.conf" ] ; then
   echo "Error:  Cannot find ${PKG}.conf."
   exit 1
fi
. ${PKG}.conf

if [ ! -d ${GIT_DIR} ] ; then
   echo "Error:  Missing directory ${GIT_DIR}"
   exit 1
fi
cd ${GIT_DIR}

../../git-commit-log ${TAG_PATTERN} > ../${PKG}.commits
