#!/bin/bash

if [ "$0" = "$(basename "$0")" ]; then
    basedir="$(dirname $(readlink -e $(which "$0")))"
else
    basedir="$(dirname $(readlink -e "$0"))"
fi

set -e

# copy values from lts-pkg-rename
eval $(grep ^lts_codename= "${basedir}/lts-pkg-rename")
eval $(grep ^codename= "${basedir}/lts-pkg-rename")
eval $(grep ^suffix= "${basedir}/lts-pkg-rename")
eval $(grep ^extraversion= "${basedir}/lts-pkg-rename")
new_package=xorg-lts-quantal
old_package=xorg
old_binaries=xserver-xorg

# xorg package is special and worth of its own script
# Only building: xserver-xorg, xserver-xorg-video-all and xserver-xorg-input-all

if [ ! -f xorg_*.tar.gz ]; then
	# This shouldn't be done on precise since we need the newer xorg
	apt-get -qq source xorg
	if [ -d xorg-7.6* ]; then
		echo "E: Precise version of xorg used?"
		exit 1
	fi
	cd xorg-7*/
else
	rm -rf -- xorg-7* xpkg
	mkdir xpkg
	cd xpkg
	tar xf ../xorg_*.tar.gz --strip-components=1
fi

old_package_version=$(head -n 1 debian/changelog | cut -d' ' -f2)
old_package_version=${old_package_version//[\(\)]/}  # Strip parens

# debian/control
# Remove any extra deps that were sneaked in from main xorg package
sed -e "s/ |[^,]*-${suffix}//g" -i debian/control

${basedir}/dpkg-control \
    --source-suffix ${suffix} \
    --binary-suffix ${suffix} \
    --mapping-file "${basedir}/lts-pkg-mapping.txt" \
    --kill-binaries x11-common,xbase-clients,xutils,xorg,xorg-dev \
    --add-replaces --add-provides --add-breaks \
     > debian/control.new

# Full list, just to make old stack gone
conflicts="Conflicts: libxatracker1 (>= 0~), libxatracker-dev (>= 0~), libgbm1 (>= 0~), libgbm-dev (>= 0~), libegl1-mesa (>= 0~), libegl1-mesa-dev (>= 0~), libegl1-mesa-drivers (>= 0~), libopenvg1-mesa (>= 0~), libopenvg1-mesa-dev (>= 0~), libgles1-mesa (>= 0~), libgles1-mesa-dev (>= 0~), libgles2-mesa (>= 0~), libgles2-mesa-dev (>= 0~), libglapi-mesa (>= 0~), libgl1-mesa-glx (>= 0~), libgl1-mesa-dri (>= 0~), libgl1-mesa-dri-experimental (>= 0~), libgl1-mesa-dev (>= 0~), mesa-common-dev (>= 0~), libosmesa6 (>= 0~), libosmesa6-dev (>= 0~), xserver-xorg-core (>= 0~), xserver-xorg-core-udeb-quantal, xserver-xorg-dev (>= 0~), xdmx (>= 0~), xdmx-tools (>= 0~), xnest (>= 0~), xvfb (>= 0~), xserver-xephyr (>= 0~), xserver-xfbdev (>= 0~), xserver-common (>= 0~),"

sed -e "/Replaces: xserver-xorg$/s@\$@\n${conflicts}@" -i debian/control.new

mv -v debian/control.new debian/control

# debian/rules
#cp "${basedir}/lts-xorg-rules" debian/rules

cp debian/rules debian/rules.new
sed -e '/$(MAKE)/d' -i debian/rules.new
sed -e '/x11-common/d' -i debian/rules.new
sed -e "s/^xserver-xorg/&-${suffix}/" -i \
    debian/xserver-xorg.lintian-overrides

for pkg in ${old_binaries}; do
    newpkg="${pkg}-${suffix}"

    echo "- Renaming ${pkg}.* files to ${newpkg}.*"

    set +e
    files=$(ls debian/${pkg}.*)
    err=$?
    set -e
    if [ $err -ne 0 ]; then
	echo "Failed to list in ${old_package} for ${old_package} -> ${new_package}"
	continue
    fi
    for old_file in $files; do
	new_file=${old_file/${pkg}/${newpkg}}
	mv -v ${old_file} ${new_file}
    # TODO: Maybe using 'rename' would be better?
    done

    # Argh my eyes, so terribly sorry about this
    # substitute $(XXV) for ati
    # dumb rename for packages install rules
    # another dumb rename for doc and bugs

    # dh_strip rules
    # libdrm has a single -p libkms1, fix it to -plibkms1

    # dh_makeshlibs is needed for libdrm
    sed -e "s@\$(XXV)@xserver-xorg-video@g" \
        -e "s@debian/${pkg}/@debian/${newpkg}/@g" \
        -e "s@debian/${pkg}\.@debian/${newpkg}.@g" \
        -e "/dh_strip/s/-p /-p/g" \
        -e "/dh_strip/s/-p${pkg} /-p${newpkg} /" \
        -e "/dh_strip/s/-N${pkg} /-N${newpkg} /" \
        -e "/dh_strip/s/${pkg}-dbg/${newpkg}-dbg/" \
        -e "/dh_makeshlibs/s/${pkg}\\([ ']\\)/${newpkg}\\1/g" \
        -e "s@${newpkg}/usr/share/doc/${pkg}@&-${suffix}@" \
        -e "s@${newpkg}/usr/share/bug/${pkg}@&-${suffix}@" \
        -e "/DEB_DBG_PACKAGE_ALL/s/ ${pkg}-dbg/ ${pkg}-${suffix}-dbg/" \
        -e "/DEB_DH_STRIP_ARGS/s/=${pkg}-dbg/=${pkg}-${suffix}-dbg/" \
        -i debian/rules.new

    if [ -f "debian/${newpkg}.symbols" ]; then
        sed -e "s/ ${pkg} / ${newpkg} /" -i "debian/${newpkg}.symbols"
    fi
done

mv debian/rules.new debian/rules

# debian/changelog
# Our version will be older than the original
dch --newversion "${old_package_version}${extraversion}" \
    --force-bad-version \
    --package xorg-${suffix} \
    --distribution ${lts_codename} \
    --force-distribution \
    "Rename package for the LTS point update, and add replaces/breaks/provides"

rm -r xsf-docs
sed -e "s/xserver-xorg[^[:space:],]*/&-${suffix}/g" -i debian/scripts/vars.*

debuild -S

cd ..
