#!/bin/bash

########################################################################
# List source packages for valid binary packages
# in lts-pkg-mapping.txt
########################################################################
# Copyright (C) 2012 Canonical, Ltd.
# Author:  Bryce W. Harrington
# License: MIT license, same as X
#          (see http://www.opensource.org/licenses/mit-license.php)
########################################################################

declare -A stack

echo "Will be renaming the following packages..."
for line in $(awk '{print $1}' lts-pkg-mapping.txt); do
    if [ -z "${line}" ] || [ ${line:0:1} = '#' ]; then
	continue
    fi
    source_package=$(apt-cache showsrc ${line} 2>/dev/null | grep ^Package: | head -n 1 | cut -d' ' -f2)
    if [ $? = 0 ] && [ ! -z "$source_package" ]; then
	if [ -z ${stack[$source_package]} ]; then
	    echo ${source_package}
	    stack[$source_package]=${source_package}
	fi
    else
	echo "Error: No source found for ${line}" 1>&2
    fi
done


echo
echo "Downloading source packages in 5 seconds..."
echo "(Hit ctrl-C to cancel)"
sleep 5

if [ ! -d Stack ]; then
    mkdir -p Stack
fi
cd Stack
for pkg in ${stack[@]} ; do
    echo $pkg
    apt-get source $pkg
done


echo
echo "Packages downloaded.  Proceding with rename in 5 seconds..."
echo "(Hit ctrl-C to cancel)"
sleep 5

for pkgdir in $(find . -type 'd') ; do
    echo
    echo $pkgdir
    (cd $pkgdir && lts-pkg-rename lts-pkg-mapping.txt)
done
