#!/bin/bash

set -e

old_binaries=xserver-xorg

# xorg package is special and worth of its own script
# Only building: xserver-xorg, xserver-xorg-video-all and xserver-xorg-input-all

# debian/control
# Remove any extra deps that were sneaked in from main xorg package
sed -e "s/ |[^,]*-${suffix}//g" -i debian/control

${basedir}/dpkg-control \
    --source-suffix ${suffix} \
    --binary-suffix ${suffix} \
    --mapping-file "${rename_mapping_file}" \
    --kill-binaries x11-common,xbase-clients,xutils,xorg,xorg-dev \
    --add-replaces --add-provides --add-conflicts \
     > debian/control.new

# Full list, just to make old stack gone
conflicts="libxatracker1 (>= 0~), libgbm1 (>= 0~), libegl1-mesa (>= 0~), libegl1-mesa-drivers (>= 0~), libopenvg1-mesa (>= 0~), libgles1-mesa (>= 0~), libgles2-mesa (>= 0~), libglapi-mesa (>= 0~), libgl1-mesa-glx (>= 0~), libgl1-mesa-dri (>= 0~), libgl1-mesa-dri-experimental (>= 0~), xserver-xorg-core (>= 0~), xserver-xorg-dev (>= 0~), xserver-xorg-video-all (>= 0~), xserver-xorg-input-all (>= 0~), ${extraconflicts}"

# add conflicts to xserver-xorg
sed -e "s/Conflicts: xserver-xorg\$/&, ${conflicts}/" -i debian/control.new

extrarecommends=""
if [ "${backport_arch}" = "precise" ]; then
	extrarecommends=", x11-xserver-utils-${suffix}"
fi

# add recommends to xserver-xorg
sed -e "s/libgl1-mesa-dri-${suffix}/&, libgl1-mesa-glx-${suffix}, linux-generic-${suffix}, xserver-xorg-input-all-${suffix}, xserver-xorg-video-all-${suffix}${extrarecommends}/" -i debian/control.new

# add xserver-xorg-renamed to provides
sed -e "s/xserver\$/&, xserver-xorg-renamed/" -i debian/control.new

mv -v debian/control.new debian/control

# debian/rules
#cp "${basedir}/lts-xorg-rules" debian/rules

cp debian/rules debian/rules.new
sed -e '/$(MAKE)/d' -i debian/rules.new
sed -e '/x11-common/d' -i debian/rules.new
sed -e "s/^xserver-xorg/&-${suffix}/" -i \
    debian/xserver-xorg.lintian-overrides

for pkg in ${old_binaries}; do
    newpkg="${pkg}-${suffix}"

    echo "- Renaming ${pkg}.* files to ${newpkg}.*"

    set +e
    files=$(ls debian/${pkg}.*)
    err=$?
    set -e
    if [ $err -ne 0 ]; then
	echo "Failed to list in ${old_package} for ${old_package} -> ${new_package}"
	continue
    fi
    for old_file in $files; do
	new_file=${old_file/${pkg}/${newpkg}}
	mv -v ${old_file} ${new_file}
    # TODO: Maybe using 'rename' would be better?
    done

    # Argh my eyes, so terribly sorry about this
    # substitute $(XXV) for ati
    # dumb rename for packages install rules
    # another dumb rename for doc and bugs

    # dh_strip rules
    # libdrm has a single -p libkms1, fix it to -plibkms1

    # dh_makeshlibs is needed for libdrm
    sed -e "s@\$(XXV)@xserver-xorg-video@g" \
        -e "s@debian/${pkg}/@debian/${newpkg}/@g" \
        -e "s@debian/${pkg}\.@debian/${newpkg}.@g" \
        -e "/dh_strip/s/-p /-p/g" \
        -e "/dh_strip/s/-p${pkg} /-p${newpkg} /" \
        -e "/dh_strip/s/-N${pkg} /-N${newpkg} /" \
        -e "/dh_strip/s/${pkg}-dbg/${newpkg}-dbg/" \
        -e "/dh_makeshlibs/s/${pkg}\\([ ']\\)/${newpkg}\\1/g" \
        -e "s@${newpkg}/usr/share/doc/${pkg}@&-${suffix}@" \
        -e "s@${newpkg}/usr/share/bug/${pkg}@&-${suffix}@" \
        -e "/DEB_DBG_PACKAGE_ALL/s/ ${pkg}-dbg/ ${pkg}-${suffix}-dbg/" \
        -e "/DEB_DH_STRIP_ARGS/s/=${pkg}-dbg/=${pkg}-${suffix}-dbg/" \
        -i debian/rules.new

    if [ -f "debian/${newpkg}.symbols" ]; then
        sed -e "s/ ${pkg} / ${newpkg} /" -i "debian/${newpkg}.symbols"
    fi
done

mv debian/rules.new debian/rules

rm -r xsf-docs
sed -e "s/xserver-xorg[^[:space:],]*/&-${suffix}/g" -i debian/scripts/vars.*

# qxl requires a spice upgrade, and there is no reason to upgrade it, so just nuke it
sed -e "/xserver-xorg-video-qxl/d" -i debian/scripts/vars.*

debuild -S ${debuild_args}
