#!/bin/bash

DISTS="hardy intrepid jaunty"
ARCHS="amd64 i386"
DEST_USER=${SUDO_USER}          # replace with your remote user account name
DEST_URL="people.ubuntu.com"    # replace with your remote site
DEST_PATH="public_html/Testing" # replace with your remote subdir (must exist)
UPLOAD=0

while getopts "u" opt $*; do
    case "$opt" in
        u ) UPLOAD=1                           ;;
        * ) warn "Unknown option '$opt'";      ;;
    esac
done
shift $(($OPTIND -1))

# Check that we're running as root
if [ $USER != 'root' ]; then
   echo "Must run as root"
   exit 1
fi

DSC=$1
if [ -z $DSC -o ${DSC%.dsc} = $DSC ]; then
    echo "Usage: $0 <pkg.dsc>"
    exit 2
fi

release=${DSC%.dsc}
version=${release#*_}
pkg=${release%_*}
pkg=${pkg#xserver-xorg-video-}
pkg=${pkg#xserver-xorg-input-}

REPORT="-------------------------------------------------------------------------"
PATTERN="%s\n%-8s %-8s   %s"
for arch in $ARCHS ; do
    for dist in $DISTS ; do
        echo
        echo "------"
        echo "ARCH=$arch DIST=$dist pbuilder build $DSC"
        ARCH=$arch DIST=$dist pbuilder build $DSC
        if [ $? -ne 0 ] ; then
            REPORT=$(printf "$PATTERN" "$REPORT" $arch $dist "FAILED:  See log for details")
            continue
        fi
        debs=$(ls /var/cache/pbuilder/$dist-$arch/result/*$version*.deb 2> /dev/null)

        if [ -z "$debs" ] ; then
            REPORT=$(printf "$PATTERN" "$REPORT" $arch $dist "FAILED:  No debs generated")
            continue
        fi

        REPORT=$(printf "$PATTERN" "$REPORT" $arch $dist "PASSED")

        for deb in $debs ; do
            REPORT=$(printf "$PATTERN" "$REPORT" "" "" $deb)
        done

        if [ $UPLOAD -eq 0 ]; then
            # Stop at this point, don't do the upload
            continue
        fi

        # Create subdir to store debs
        path="$DEST_PATH/$pkg/$dist-$arch"
        echo "ssh $DEST_URL mkdir $path"
        sudo -u $DEST_USER ssh "$DEST_URL" "mkdir -p $path"

        # Upload the debs
        for deb in $debs ; do
            echo "scp $deb $DEST_URL:$path"
            sudo -u $DEST_USER scp "$deb" "$DEST_URL:$path"
        done
    done
done

echo "$REPORT"


