#!/bin/sh -e

DRIVERS="$@"

AUTOXORGGIT=$(dirname $0)/auto-xorg-git

if [ ! -x $AUTOXORGGIT ]; then
    echo "Can not execute $AUTOXORGGIT"
    exit 1
fi

for PACKAGE in $DRIVERS; do
    echo
    echo "=================================="
    echo "Building $PACKAGE"
    echo "=================================="
    mkdir -p auto-$PACKAGE/uploaded
    mv auto-$PACKAGE/*source.changes auto-$PACKAGE/uploaded 2>/dev/null || true
    [ $PACKAGE = mesa ] && P="-p" || P=""
    $AUTOXORGGIT $HOOKS -o -n -w auto-$PACKAGE $P $PACKAGE
    dput $PPA auto-$PACKAGE/*source.changes || true
done
